SELECT * FROM customers;

-- Questions:
-- Q.What is the total revenue generated by male and female customers :
SELECT 
	gender,
	SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY gender;

-- Q.Which customer used a discount but still spend more than average purchase amount :
WITH PURCHASE_DISCOUNT AS(
SELECT 
	AVG(purchase_amount) AS avg_purchase
FROM customers 
)
SELECT 
C.customer_id,
C.purchase_amount
FROM customers C
CROSS JOIN PURCHASE_DISCOUNT PD
WHERE discount_applied = 'Yes' AND purchase_amount>avg_purchase;

-- Q.Which are the top 5 products with the highest average review ratings :
SELECT TOP 5
	item_purchased,
	ROUND(AVG(review_rating),2) AS avg_rating
FROM customers
WHERE review_rating IS NOT NULL
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC;

-- Q.Compare the average purchase amount between standard and express shipping :
SELECT 
	shipping_type,
	AVG(purchase_amount) AS avg_purchase_amount
FROM customers
WHERE shipping_type IN('Standard','Express')
GROUP BY shipping_type

-- Q.Do subscribed customer spend more? Compare average spend and total revenue between subcriber and non subscriber :
SELECT 
	subscription_status,
	COUNT(customer_id) AS total_customer,
	SUM(purchase_amount) AS total_revenue,
	AVG(purchase_amount) AS avg_purchase
FROM customers
GROUP BY subscription_status

-- Q.Which 5 products have the highest percentage of purchase with discount applied :
SELECT TOP 5
	item_purchased,
	SUM(CASE WHEN discount_applied='Yes' then 1 else 0 end)*100/ COUNT(*) AS discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate DESC;

-- Q.Segment customers into New, Returning and Loyal based on their total number of previous purchase 
-- and show count of each segment :
WITH CUSTOMER_TYPE AS(
SELECT 
	previous_purchases,
	CASE WHEN previous_purchases<=5 THEN 'New'
			WHEN previous_purchases BETWEEN 6 AND 20 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
FROM customers
)
SELECT 
	COUNT(*) AS no_of_customers,
	customer_segment
FROM CUSTOMER_TYPE
GROUP BY customer_segment;

-- Q.What are the top most purchased product within each category :
WITH TOP_PURCHASED AS(
SELECT 
	category,
	item_purchased,
	COUNT(*) AS total_customer,
	ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS Ranks
FROM customers
GROUP BY category,
item_purchased
)
SELECT 
	category,
	item_purchased,
	total_customer,
	Ranks
FROM TOP_PURCHASED
WHERE Ranks<=3

-- Q.Are customers who are repeated buyers (More than 5 previous purchase) also likely to subcribed :
SELECT 
	COUNT(customer_id) AS repeat_buyer,
	subscription_status
FROM customers
WHERE previous_purchases>5
GROUP BY subscription_status;

-- Q.What is the reveneue contribution for each age group :
SELECT 
	age_group,
	SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY age_group
ORDER BY total_revenue DESC;
